# https://www.hackerrank.com/challenges/find-second-maximum-number-in-a-list
if __name__ == '__main__':
    n = int(input())
    str = input()
    str_list = str.split(" ")
    arr_list = list(map(int, str_list))
    print(arr_list)
    arr_list.sort()
    print(arr_list)
    MAX = max(arr_list)
    print(MAX)
    N = arr_list.count(MAX)
    print(N)
    print(len(arr_list))
    second = arr_list.pop(len(arr_list) - N - 1)
    print(second)
